# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://emmanguyen.github.io/
# baseurl: http://emmanguyen.github.io/
baseurl:
title: Emma Phuong Nguyen
author: Emma Phuong Nguyen
description: Personal blog and resume
avatar: profile.png
email: emma.mphuong@gmail.com
github: emmanguyen # username
twitter: emmaphuongng
linkedin: mphuongn
facebook: emma.phuong.ng
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-71895375-1


# needed for travis-ci build
exclude: [vendor]
